name: 'Git Setup'
description: 'Setup Git configuration for automated commits and tags'

inputs:
  fetch-depth:
    description: 'Git fetch depth'
    required: false
    default: '0'
  user-name:
    description: 'Git user name'
    required: false
    default: 'github-actions[bot]'
  user-email:
    description: 'Git user email'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up Git user
      shell: bash
      run: |
        git config user.name "${{ inputs.user-name }}"
        git config user.email "${{ inputs.user-email }}"
        echo "✅ Git configured with user: ${{ inputs.user-name }}"
