name: Test

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '18'
        type: string
      pnpm-version:
        description: 'pnpm version to use'
        required: false
        default: '8'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: zee-sandev/devops/.github/actions/setup@main
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}

      - name: Run tests
        run: |
          if pnpm run | grep -q "test"; then
            pnpm run test
          else
            echo "No test script found in package.json"
            exit 1
          fi
