name: Deploy

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to deploy (e.g., dev-v1.2.3, qa-v1.2.3, prd-v1.2.3)'
        required: true
        type: string
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '18'
        type: string
      pnpm-version:
        description: 'pnpm version to use'
        required: false
        default: '8'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set deployment environment
        id: set-env
        run: |
          TAG="${{ inputs.tag }}"
          if [[ "$TAG" == dev-v* ]]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == qa-v* ]]; then
            echo "env=staging" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == prd-v* ]]; then
            echo "env=production" >> $GITHUB_OUTPUT
          else
            echo "Unknown tag pattern: $TAG"
            exit 1
          fi

      - name: Setup Node.js and pnpm
        uses: zee-sandev/devops/.github/actions/setup@main
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}

      - name: Production deployment confirmation
        if: ${{ steps.set-env.outputs.env == 'production' }}
        run: |
          echo "🚨 PRODUCTION DEPLOYMENT CONFIRMATION 🚨"
          echo "=================================="
          echo "Environment: ${{ steps.set-env.outputs.env }}"
          echo "Tag: ${{ inputs.tag }}"
          echo "=================================="
          echo "This action will deploy to production!"
          echo "Please ensure all necessary approvals are in place."

      - name: Deploy with pnpm
        run: |
          ENV="${{ steps.set-env.outputs.env }}"
          if pnpm run | grep -q "deploy"; then
            pnpm run deploy -- --env "$ENV"
          else
            echo "No deploy script found in package.json"
            exit 1
          fi